<?php include 'tmpl_top.php'; ?>

<div id="bangKok">
    <h2>BANGKOK</h2>
        <div>
            <article class="description">
                <p><b>Thème :</b> Capitale, Grande ville, culture, fête.</p>
                <p><b>Localisation :</b> Située dans le delta du fleuve Chao Phraya.</p>
                <p><b>Accès:</b> Desservi par 2 aéroports, l’aéroport de Bangkok-Suvarnabhumi et l’aéroport international Don Muang.</p>
                <p><b>Climat :</b> Haute saison de novembre à février, 22/32 C° Saison des pluies : de mai à novembre.</p>
                <p><b>Présentation :</b> Capitale de la Thaïlande Bangkok accueil plus de 8 millions d’habitants. La ville est connue pour ses sanctuaires richement décorés et ses rues animées. Elle est partagée en deux par le fleuve Chao Phraya. Sur sa rive droite, on trouve la partie la plus traditionnelle de la cité, traversée de canaux reliés au fleuve, et sur la rive gauche, se dresse la partie la plus importante avec les lieux touristiques et les quartiers modernes.</p>
                    <h3><b>Le nom complet de la ville signifie :</b></h3>
                        <p><q>Ville des dieux, grande ville, résidence du Bouddha d’émeraude, ville imprenable du dieu Indra, grande capitale du monde ciselée de neuf pierres précieuses, ville heureuse, généreuse dans l’énorme Palais Royal pareil à la demeure céleste, règne du dieu réincarné, ville dédiée à Indra et construite par Vishnukarn </q></p>
            </article>
            <div class="df_bangkok">
                <h3><b>Les incontournables :</b></h3>
                <div class="incontournable">
                    <article class="img_zoom_hover">
                        <figure class="img_zoom">
                            <img src="img/le_grand_budha_bk.jpg" alt="le_grand_budha_bk">
                            <figcaption><small><em>Le Grand Palais : et son Bouddha d’émeraude, emblème national.</em></small></figcaption>
                        </figure>
                    </article>
                    <article class="img_zoom_hover">
                        <figure class="img_zoom">
                            <img src="img/Wat_Pho.jpg" alt="Wat Pho">
                            <figcaption><small><em>Le Wat Pho et son grand bouddha couché : Boudha couché de 45m de long, plus ancien temple.</em></small></figcaption>
                        </figure>
                    </article>
                    <article class="img_zoom_hover">
                        <figure class="img_zoom">
                            <img src="img/temple.png" alt="temple">
                            <figcaption><small><em>Wat Arun Temple de l’aube en mosaïques Le prang (flèche) du Chao Phraya est l'un des monuments les plus célèbres de Bangkok plus de 70 mètres de haut et est joliment décorée de minuscules morceaux de verre coloré et de porcelaine.
                            </em></small></figcaption>
                        </figure>
                    </article>
                </div>
            </div>
        </div>
        <div class="df_bangkok">
            <h3><b>Le Wat Saket :</b></h3>
            <div class="incontournable2">
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/wat_saket.png" alt="wat_saket">
                        <figcaption><small><em>Construit sur une colline artificielle de 75m de haut, il offre une magnifique vue sur la ville. Son Chedi doré renfermait une partie des véritables cendres du Bouddha.</em></small></figcaption>
                    </figure>
                </article>
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/wat_saket_1.png" alt="wat_saket_1">
                        <figcaption><small><em>Construit sur une colline artificielle de 75m de haut, il offre une magnifique vue sur la ville. Son Chedi doré renfermait une partie des véritables cendres du Bouddha.</em></small></figcaption>
                    </figure>
                </article>
            </div>
        </div>
        <div class="df_bangkok">
            <h3><b>Maison de Jim :</b></h3>
            <div class="incontournable">
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/maison_jim.png" alt="maison_jim">
                        <figcaption><small><em>Maison de Jim Thompson</em></small></figcaption>
                    </figure>
                </article>
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/maison_jim1.png" alt="maison_jim1">
                        <figcaption><small><em>Maison de Jim Thompson</em></small></figcaption>
                    </figure>
                </article>
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/maison_jim2.png" alt="maison_jim2">
                        <figcaption><small><em>Maison de Jim Thompson</em></small></figcaption>
                    </figure>
                </article>
            </div>  
        </div>                       
</div>


<?php include 'tmpl_bottom.php'; ?>