<?php include "tmpl_top.php"; ?>

<section id="equipe">
    <article>
        <figure>
            <img src="img/Leila.jpeg" alt="Photo Leila">
            <figaption>Designer</figaption>
        </figure>
        <h2>LEILA DIAF - Chef De Projet</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde eveniet sequi exercitationem non, minima nam at quasi eligendi libero necessitatibus ab excepturi sunt repellat nesciunt magni sed enim odit totam impedit cum, veniam culpa nobis! Alias quos molestiae dolores laudantium!</p>
    </article>
    <article>
        <figure>
            <img src="img/yann.jpeg" alt="Photo Yann">
            <figaption>Developpeur</figaption>
        </figure>
        <h2>YANN CALIBET - Directeur des nouvelles techno. (CTO)</h2>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde ad doloribus consequuntur dolores delectus quibusdam quas modi! Ab, ad. Nihil, eligendi! Soluta praesentium nulla amet exercitationem neque eaque possimus excepturi minus sint expedita, fuga recusandae numquam reiciendis nam laborum pariatur?</p>
    </article>
</section>

<?php include "tmpl_bottom.php"; ?>