<?php include 'tmpl_top.php'; ?>

<div id="phuket">
    <h2>HUA-HIN</h2>
    <div>
        <article class="description">
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/huahin_plage.jpg" alt="Plage de huahin">
                        <figcaption><small><em>Plage Phuket</em></small></figcaption>
                    </figure>
                    <figure class="img_zoom">
                        <img src="img/huahinStation.jpg" alt="station balnéaire">
                        <figcaption><small><em>Ville balnéaire</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p><b>Thème :</b> En famille, ville balnéaire.</p>
                    <p><b>Localisation :</b> Située à seulement 3 heures en voiture au sud de Bangkok.</p>
                    <p><b>Accès :</b> En voiture ou en bus durée du trajet environ 3h00. En train le trajet est un peu plus long compter environ 4 heures.</p>
                    <p><b>Climat :</b> Saison des pluies de mai à octobre. Les mois les plus favorable pour se rendre à Hua hin sont : de janvier à avril et de octobre à décembre.</p>
                    <p><b>Présentation :</b> Hua Hin était autrefois un simple village de pêcheur, désormais, c’est la première station balnéaire de Thaïlande. Situé à 3 heures en voitures de Bangkok elle est surnommée le « Deauville Thaïlandais ». Elle attire de nombreux touristes avec ses belles plages, son golf, ses parcs aquatiques, ses différents marchés.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Les incontournables :</b></h3> 
            <h3><b>Hua Hin Railway Station</b></h3> 
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/Hua-Hin-Train-Station.jpg" alt="Hua Hin Railway Station">
                        <figcaption><small><em>Hua Hin Railway Station</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">   
                    <p>Fierté de la population locale, la gare ferroviaire, construite sous le règne de Rama VI, est l'une des plus anciennes du pays. Son charme esthétique est tout à fait à la hauteur de son poids historique. La salle d'attente royale, alors établie pour accueillir le roi et ses proches, se trouve juste à côté du hall où patientent toujours des voyageurs.</p> 
                </div>
            </div>   
        </article>
    </div>
    <div>
        <article class="description">
        <h3><b>Le Cicada Market</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/cicada-market.jpg" alt="Le Cicada Market">
                        <figcaption><small><em>Le Cicada Market</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>Marché de nuit, tendance, avec une ambiance décontractée et authentique ! Idéal pour passer un moment de détente, et admirer les différentes scènes artistiques émergeantes, de nombreux étudiants des écoles d’art viennent y exposer et présenter leurs œuvres.Le marché est divisé en quatre parties : Art A la mode, Cicada Art Fatory, Amphitheatre et Cicada Cuisine.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Vana Nava Hua Hin Water jungle</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/vana-water-park.jpg" alt="Vana Nava">
                        <figcaption><small><em>Vana Nava Hua Hin Water jungle</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>A seulement 5 min du centre-ville de Hua Hin se trouve le VANA NAVA, c’est le premier parc de jeux aquatiques d’Asie. On y trouve le plus grand Toboggan de Thaïlande et la plus grande chute d’eau artificielle d’Asie !</p>
                </div>
            </div>
        </article>
    </div>
    <div>
        <article class="description">
            <h3><b>Inu Cafe</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/inu_cafe.jpg" alt="Inu Cafe">
                        <figcaption><small><em>Inu Cafe</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>Hua hin regorge de café insolite nous avons choisis de vous parlé de l’Inu café. Un lieu parfait pour les amoureux des chiens, vous dégusterez de bons plats thaïlandais ou occidentaux entouré de petits Shiba Inu.</p>
                </div>
            </div>
        </article>
</div>

<?php include 'tmpl_bottom.php'; ?>