<?php include 'tmpl_top.php' ?>
<div class="div_article">
  <section class="BangKok">
    <div class="zone_de_texte">
      <article>
        <h2>BANGKOK</h2>
          <p>Ville des dieux, grande ville, résidence du Bouddha d’émeraude, ville imprenable du dieu Indra, grande capitale du monde ciselée de neuf pierres précieuses[...]</p>
            <a href="bangKok.phtml">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
      </article>
    </div>
  </section>
  <section class="KohSamui">
  <div class="zone_de_texte">
    <h2>KOHSAMUI</h2>
      <article>
        <p>Koh Samui est une île du Golfe de Siam, se trouvant au large de la côte Est de la Thaïlande, juste sous l’île de Ko Pha Ngan[...]</p>
        <a href="kohSamui.phtml">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
      </article>
      <div>
  </section>
</div>
<div class="div_article">
  <section class="HuaHin">
    <div class="zone_de_texte">
      <h2>HUA-HIN</h2>
        <article>
          <p>Hua Hin, station balnéaire de Thaïlande située dans la Province de Prachuap Khiri Khan. Elle se trouve au nord de la péninsule Malaise[...]</p>
          <a href="hua_hin.phtml">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
        </article>
    </div>
  </section>
  <section class="KohPhiPhi">
    <div class="zone_de_texte">
      <h2>KOH-PHIPHI</h2>
        <article>
          <p>Les îles Phi Phi sont un petit archipel de Thaïlande situé dans la mer d'Andaman au large de la province de Krabi, à laquelle il appartient[...]</p> 
          <a href="kohPhiphi.phtml">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
        </article>
    </div>
  </section>
</div>
<div class="div_article">
  <section class="Phuket">
    <div class="zone_de_texte">
      <h2>PHUKET</h2>
        <article>
          <p>La ville de Phuket, sur l'île de Phuket, est la capitale de la province thaïlandaise du même nom. Dans la vieille ville, la route de Thalang est bordée de "shophouses"[...]</p>
          <a href="phuket.phtml">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
        </article>
    </div>
  </section>
  <section class="KohLanta">
    <div class="zone_de_texte">
      <h2>KOH-LANTA</h2>
        <article>
          <p>Il s’agit d’un petit village situé sur la côte Est de Koh Lanta, c’est une région mélangeant de nombreuses cultures : des marchands chinois, des familles[...]</p>
          <a href="kohLanta.phtml">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
        </article>
      </div>
  </section>
</div>
<div class="div_article">
  <section class="tokyo">
    <div class="zone_de_texte">
      <h2>Tokyo</h2>
        <article>
          <p>Tokyo c’est la ville de la démesure! La mégalopole est l’aire urbaines la plus peuplés au monde, 38 millions de personne s’y croisent chaque jours[...] </p>
            <a href="tokyo.phtml">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
        </article>
      </div>
  </section>
  <section class="Kyoto">
    <div class="zone_de_texte">
      <h2>Kyoto</h2>
        <article>
          <p>Kyoto est l’ancienne capitale du Japon, cette ville traditionnelle compte 2000 temples Bouddhistes et Shintoïstes dont 17 inscrits au patrimoine mondiale de l’UNESCO[...]</p>
            <a href="kyoto.phtml">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
        </article>
      </div>
  </section>
</div>
<div class="div_article">
    <section class="osaka">
      <div class="zone_de_texte">
        <h2>Osaka</h2>
          <article>
            <p>Osaka est la troisième plus grande ville du Japon. Elle est complètement différente de Tokyo, c’est la ville un peu rebelle du Japon. La mentalité est un peu plus, vivante, vibrante[...]</p>
              <a href="osaka.phtml">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
          </article>
      </div>
    </section>
    <section class="kanagawa">
      <div class="zone_de_texte">
        <h2>Kanagawa</h2>
          <article>
            <p>Kanagawa est une préfecture assez petite mais très peuplée, au sud-ouest de Tokyo, sur l’île principale de Honshu. Elle est située dans la plaine du Kanto, donnant sur l’océan Pacifique[...]</p>
              <a href="#">Envolez vous <i class="fab fa-avianex fa-2x"></i></a>
          </article>
      </div>
    </section>
</div>  
<?php include 'tmpl_bottom.php'; ?>