<?php include "tmpl_top.php"; ?>
<div id="kohLanta">
    <h2>KOHLANTA</h2>
    <div>
        <article class="description">
            <h3><b>Lanta Old Town</b> </h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/oldtown.jpg" alt="Lanta Old Town">
                        <figcaption><small><em>Lanta Old Town</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Il s’agit d’un petit village situé sur la côte Est de Koh Lanta, c’est une région mélangeant de nombreuses cultures : des marchands chinois, des familles de pêcheurs thaïes et des anciennes communautés de marins. Il y a des années de cela, l’ancienne ville (Lanta Old Town) était le centre commercial de l’île et elle possédait son unique port. C’était un lieu d’échange sûr pour les navires marchands arabes et chinois. Aujourd’hui, l’ancienne ville est un district important, elle possède un service de Poste, un commissariat de police, un temple bouddhiste, un temple chinois, un port et l’unique hôpital de l’île. C’est un lieu agréable à visiter, on y trouve une multitude de restaurants de qualité et des boutiques intéressantes avec des produits artisanaux, tels que des hamacs, des peintures et des œuvres d’art en batik</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Ban Saladan</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/banSaladan.jpg" alt="Ban Saladan">
                        <figcaption><small><em>Ban Saladan</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">   
                    <p>Situé à trois kilomètres de la plage de Klong Dao, Ben Saladan est un lieu touristique où vous pourrez profiter de nombreuses excursions, faire de la plongée ou encore du shopping.</p> 
                </div>
            </div>   
        </article>
    </div>
    <div>
        <article class="description">
            <h3><b>Khao Mai Kaew Caves</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/kaewCave.jpeg" alt="Kaew Caves">
                        <figcaption><small><em>Khao Mai Kaew Caves</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Les caves de Khao Mai Kaew se trouvent dans le centre de l’île, celles-ci disposent de magnifiques roches et d’impressionnantes stalactites et stalagmites. Pour visiter ces caves, vous aurez besoin d’un guide, cela coûte 200 bahts par personne. Vous pourrez également faire une balade en éléphant pour 600 bahts.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Sea-Gypsy village</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/sea_gypsy_village.jpg" alt="Sea-Gypsy">
                        <figcaption><small><em>Sea-Gypsy village</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Connu sous le nom de Chao Le par les thais, les gitans de la mer ont occupé cette zone durant plusieurs centaines d’années. Les gitans de la mer vivent à part et ne se mélangent pas trop aux autres populations locales. Ils ont leurs propres coutumes, croyances, rituels et même leur propre langage.</p>
                </div>
            </div>
        </article>
    </div>
    <div>
        <article class="description">
            <h3><b>Orchid nursery farm</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/orchid_nursery_farm.jpg" alt="Orchid nursery">
                        <figcaption><small><em>Orchid nursery farm</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Si vous aimez les fleurs, ce parc ne pourra que vous plaire. Ce parc d’orchidées se trouve à proximité de la plage Pra Ae et l’entrée coûte 30 bahts par personne.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Koh Lanta Noi</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/lantaNoi.jpg" alt="Lanta Noi">
                        <figcaption><small><em>Koh Lanta Noi</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Vous ne trouverez pas d’hébergement ou d’activités touristiques à Lanta Noi, mais c’est un endroit qui vaut vraiment le détour. Vous pourrez vous y rendre en bateau depuis le port de Saladan ou en moto. Sur place, vous pourrez découvrir la vie courante des autochtones et savourer la nourriture locale.</p>
                </div>
            </div>
        </article>
    </div>
    <div>
        <article class="description">
            <h3><b>Kor Kwang</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/kawkwang.jpg" alt="Kor Kwang">
                        <figcaption><small><em>Kor Kwang</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Cette plage possède un joli sable et une eau très claire.</p> 
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Klong Dao</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/Khlong_Dao_Beach.jpg" alt="Klong Dao">
                        <figcaption><small><em>Klong Dao</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Au fil des années, Klong Dao est devenue la plage la plus populaire de l’île. Étendue sur 3 kilomètres de long de sable blanc et une eau claire, la plage de Klong Dao n’est jamais remplie et elle ne se trouve qu’à 2 kilomètres du port Saladan. Le long de la plage se trouve un grand nombre d’hôtels plus ou moins prestigieux, pouvant aller de quelques centaines de bahts la nuit, à quelques milliers. C’est un lieu idéal pour ceux qui souhaitent disposer d’une plage tranquille tout en étant à proximité de restaurants internationaux et de bars.</p>
                </div>
            </div>
        </article>
    </div>
    <div>
        <article class="description">
            <h3><b>Pra Ae</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/phra_aeKo_Lanta_Beach.jpg" alt="Pra Ae">
                        <figcaption><small><em>Pra Ae</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Aussi connue sous le nom de Long Beach, la plage de Pra Ae se situe dans le Nord de l’île et forme un croissant sur 4 kilomètres de long. C’est un coin tranquille où vous trouverez aisément des hôtels et des bungalows.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Klong Khong</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/Khlong_Khong_Beach.jpg" alt="Klong Khong">
                        <figcaption><small><em>Klong Khong</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Cette plage est longée par une petite rivière et une ancienne plantation de cocotiers, alors qu’un récif corallien longe la rive. Ainsi, la natation y est déconseillée mais le coucher de soleil est splendide.</p>
                </div>
            </div>
        </article>
    </div>
    <div>
        <article class="description">
            <h3><b>Klong Nin</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/klongNin.jpg" alt="klong Nin">
                        <figcaption><small><em>Klong Nin</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Séparée en deux par une rivière, cette plage est couverte de cocotiers et de pins. Comme la plupart des plages de Koh Lanta, Klong Nin offre une atmosphère paisible et agréable, avec son sable blanc et fin. Pour la baignade, il vous sera conseillé de vous rendre dans la partie Nord de la plage qui est moins rocailleuse que la partie Sud.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Kan Tiang</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/kantiang.jpg" alt="an Tiang">
                        <figcaption><small><em>Kan Tiang</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Cette petite plage ne s’étend que sur un kilomètre de long, elle offre donc moins d’espace privé que les autres plages de Koh Lanta. Cependant, Kan Tiang est un lieu idéal pour la plongée en apnée, car on y trouve de magnifiques coraux. Localisée à 18 kilomètres au Sud de Baan Saladan, Kan Tiang est l’une des plus belles plages de l’île.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>les plages Ao Nui (Nui Bay) et Had Hin Ngam</b></h3>
            <div class="flex_kohLanta">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/nui_bay.jpg" alt="Nui Bay">
                        <figcaption><small><em>Les plages Ao Nui (Nui Bay) et Had Hin Ngam</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_kohLanta">
                    <p>Quelques autres plages dans le Sud de Koh Lanta valent également la peine d’être visitées. Elles ne font que quelques centaines de mètres de long, elles sont très calmes et on y trouve quelques bungalows et des chambres d’hôtel. Par exemple, les plages Ao Nui (Nui Bay) et Had Hin Ngam, qui se trouvent dans le parc national de Koh Lanta, sont des lieux sympa pour se reposer et être loin de la foule</p>
                </div>
            </div>
        </article>
    </div>
</div>
<?php include "tmpl_bottom.php"; ?>
