<?php include 'tmpl_top.php'; ?>

<div id="kohPhiphi">
    <h2>LES ÎLES PHIPHI</h2>
    <div>
        <article class="description">
            <h3><b>Thème : Nature, plongée, île paradisiaque</b></h3>
                <p>Localisation : Les îles Phi Phi sont un petit archipel situé dans la mer d’Andaman.
                Accès : Pour rejoindre Koh Phi Phi il faudra emprunter un Ferry, qui vous emmènera au port de Tonsai.
                Climat : haute saison de novembre à avril. Entre janvier vous profiterez de la meilleur visibilité pour faire de la plongée.</p>
            <h3><b>Présentation :</b></h3>
                <p>L’archipel comporte 6 îles, les deux îles principales sont :<br> 
                Ko Phi Phi Don est la plus grande des îles et c’est la seule qui est doté d’infrastructure pouvant accueillir les touristes.
                Ko Phi Phi Le, est l’île la plus célèbre. Elle doit sa renommé à ses paysages paradisiaques. Elle est cependant totalement inhabitée et a servi de décors au film « La plage » avec Leonardo Di Caprio.
                L’archipel est considéré comme l’un des plus beaux au monde caractérisé pas ses immenses falaises de calcaire et ses eaux translucides. Complètement ravagé en 2004 à la suite du Tsunami il a été reconstruit depuis.</p><br>
            <h3><b>Les incontournables :</b></h3>
                <p>Sur l’île de ko phi Phi Don :</p>
                <p>Le Phi Phi viewpoint :</p>
                <p>Il offre une vue magnifique sur l’île depuis les hauteurs. Une ascension de 20 à 30 minutes est nécessaire pour y arriver.:</p>
        </article>
        <div class="df_kohphiphi">
            <h3><b>Nui Bay : </b></h3>
            <div class="incontournable">
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/nui_bay_plage1.png" alt="nui_bay_plage1">
                        <figcaption><small><em>Plage de sable blanc encastré entre les falaises et végétation abondante.</em></small></figcaption>
                    </figure>
                </article>
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/nui_bay_plage2.png" alt="nui_bay_plage2">
                        <figcaption><small><em>Envie de découvrir de belles plages tranquilles ?</em></small></figcaption>
                    </figure>
                </article>
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/plage-baie-nui-bay.jpg" alt="nui_bay_plage3">
                        <figcaption><small><em>On pique une tête ?</em></small></figcaption>
                    </figure>
                </article>
            </div>
        </div>
        <div class="df_kohphiphi">
            <h3><b>Maya Bay :</b></h3>
            <div class="incontournable2">
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/maya_bay_plage1.png" alt="maya_bay_plage1">
                        <figcaption><small><em>plage mythique décors du film « La plage »</em></small></figcaption>
                    </figure>
                </article>
                <article class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/maya_bay_plage2.png" alt="maya_bay_plage2">
                        <figcaption><small><em>Envie de découvrir de belles plages tranquilles ?</em></small></figcaption>
                    </figure>
                </article>
            </div>
                <h3><b>Bonnes adresses :</b></h3>
                    <p>Snorkeling : Le meilleur spot se trouve Ko Mai Phai ( Bamboo Island ).</p>
                    <p>Kayak : Meilleur moyen pour admirer les falaises, plusieurs endroits ou les louer à Tonsai.</p>
                <h3><b>Food :</b></h3>
                    <p>Anna’s Restaurant</p>
                    <p>Unni’s restaurant</p>
                    <p>Grand PP Arcade</p> 
        </div>         
    </div>
</div>
<?php include 'tmpl_bottom.php'; ?>