<?php include 'tmpl_top.php'; ?>
<div id="kohSamui">
    <h2>KOH-SAMUI</h2> 
        <div class="page_koh_samui">
            <article class="description">
                <h3><b>Une île paradisiaque</b></h3>
                    <p>Koh Samui est une île du Golfe de Siam, se trouvant au large de la côte Est de la Thaïlande, juste sous l’île de Ko Pha Ngan. Elle est la plus grande île des 80 archipels du Parc National de Angthong, et la troisième plus grande île de Thaïlande derrière Phuket et Koh Chang.</p>
            </article>
            <article class="description">
                <h3><b>Le temple de Wat Plai Laem</b></h3>
                <div class="flex_samui">
                    <div class="img_zoom_hover">
                        <figure class="img_zoom">
                            <img src="img/temple_kohsamui.jpg" alt="temple_kohsamui">
                            <figcaption><small><em>Le temple de Wat Plai Laem</em></small></figcaption>
                        </figure>
                    </div>
                    <div class="texte_samui"> 
                        <p>Impossible de visiter la Thaïlande sans admirer ses nombreux temples ! Sur la côte nord est de Koh Samui, Wat Plai Laem est un incontournable. Ce temple bouddhiste très coloré se distingue par la présence de son immense statue de 18 mètres : il s’agit de la déesse à 18 bras Guanyin, déesse de la miséricorde et de la compassion. A l’intérieur, de magnifiques fresques racontent l’histoire de Bouddha.</p>
                    </div> 
                </div>
            </article>
            <article class="description">
                <h3><b>Hin Ta et Hin Yai</b></h3>
                <div class="flex_samui">
                    <div class="img_zoom_hover">
                        <figure class="img_zoom">
                            <img src="img/hinTa.jpg" alt="hinTa">
                            <figcaption><small><em>Hin Ta et Hin Yai</em></small></figcaption>
                        </figure>
                    </div>  
                    <div class="texte_samui">
                        <p>Aussi appelées « Grand Father and Grand Mother Rocks« , ces formations rocheuses attirent tout particulièrement les visiteurs. Situées au sud de la plage de Lamai, elles ont en effet la particularité de ressembler à… des organes génitaux féminins et masculins ! La légende locale raconte d’ailleurs que les corps de deux vieux amants se seraient échoués dans la baie après le naufrage de leur bateau, créant ainsi ces sculptures dans la roche.</p>
                    </div>
                </div>
            </article>
            <article class="description">
                <h3><b>Secret Buddha Garden</b></h3>
                <div class="flex_samui">
                    <div class="img_zoom_hover">
                        <figure class="img_zoom">
                            <img src="img/magicGarden.png" alt="magicGarden">
                            <figcaption><small><em>"Magic Garden"</em></small></figcaption>
                        </figure>
                    </div>  
                    <div class="texte_samui">
                        <p>Le secret budha garden se trouve sur les hauteurs de l’île, à environ 500 mètres d’altitude. Mais il faut avouer qu’il est assez difficile à trouver, donc n’hésitez pas à demander votre chemin aux locaux (là bas, ils l’appellent plutôt le "Magic Garden" ). Plusieurs représentations divines, bouddhas et animaux y ont été sculptées dans la pierre, tout autour d’une petite cascade. L’endroit est assez petit, mais très reposant et propice à la relaxation.</p>
                    </div>
                </div>
            </article>
            <article class="description">
                <h3><b>Les cascades Nam Tok Na Muang</b></h3>
                <div class="flex_samui">
                    <div class="img_zoom_hover">
                        <figure class="img_zoom">
                            <img src="img/cascades.png" alt="cascades">
                            <figcaption><small><em>Les cascades Nam Tok Na Muang</em></small></figcaption>
                        </figure>
                    </div> 
                    <div class="texte_samui">
                        <p>D’une hauteur de 30 mètres, Nam Tok Na Muang héberge notamment un bassin dans lequel vous pourrez vous baigner et admirer les paysages aux alentours. Deux autres cascades se trouvent également non loin de là : Na Muang 2, la plus petite, et Nam Tok Wang Saotong, impressionnante et accessible par une route récemment rénovée.</p>
                    </div> 
                </div>
            </article>
            <article class="description">
                <h3><b>La plage Chaweng</b></h3>
                <div class="flex_samui">
                    <div class="img_zoom_hover">
                        <figure class="img_zoom">
                            <img src="img/plage_kohSamui.png" alt="La_plage_Chaweng">
                            <figcaption><small><em>La plage Chaweng</em></small></figcaption>
                        </figure>
                    </div>
                    <div class="texte_samui">  
                        <p>La plage Chaweng, située sur la partie Nord-Est de l’île, offre un bon compromis aux vacanciers : à la fois idyllique pour son cadre – sable fin, eau turquoise et cocotiers – elle plait aussi aux fêtards le soir, en raison de ses nombreux restaurants et night-clubs. Vous pourrez y siroter une eau de coco, opter pour une session de jet ski ou tout simplement bronzer tranquillement au soleil.</p>
                    </div>
                </div>
            </article>
        </div>
</div>
<?php include 'tmpl_bottom.php'; ?>