<?php include "tmpl_top.php"; ?>
<div id="KYOTO">
    <h2>KYOTO</h2>
    <section>
    	<article class="description">
            <img src="img/kyoto.jpg" alt="KYOTO" />
            <p><b>Thème : </b> Culture, tradition.</p>
            <p><b>Localisation : </b>Située dans le centre de l'île de Honshu.</p>	
            <p><b>Accès : </b>À 2h40 de Tokyo en train, via le Shinkansen. Une fois sur place il est très facile de se déplacer en transport en commun.</p>
            <p><b>Climat: </b>Le climat est tempéré vous pourrez donc visiter Kyoto toute l’année. La périodes de cerisiers à fleurs de fin mars à début avril est cependant très prisé.</p>
            <p><b>Présentation : </b>Kyoto est l’ancienne capitale du Japon, cette ville traditionnelle compte 2000 temples Bouddhistes et Shintoïstes dont 17 inscrits au patrimoine mondiale de l’UNESCO. Un véritable mélange de tradition et de modernité qui fait tout le charme de la ville et du Japon de manière plus générale. Vous pourrez vous loger dans de superbe Ryokan, parmis les meilleurs du pays.</p>
    	</article>
    </section>
    <section class="incontournables">	
    	<h3>Les incontournables :</h3>
    	<article class="Gion flex">
			<figure>
				<img src="img/Gion.png" alt="Gion" />
			</figure>
			<p><b>Quartier Gion :</b>Situé au au coeur de la ville, c’est le quartier historique. Il n’est pas rare d’y croiser des Geishas. Le quartier est très typique on y trouve de nombreuses maisons traditionnelle.</p>
    	</article>
    	<article class="pavillonor flex">
    		<figure>
    			<img src="img/pavillonor.png" alt="Le pavillon d'Or" />
    		</figure>
    		<p><b>Le pavillon d'Or : </b>Le temple Rokuon-ji plus est communément appelé Kinkaji-ju. Le temple bouddhiste est recouvert de feuille qui se reflètent sur l'étang qui l’entoure. Nous ne pouvons malheureusement pas entrer dans le pavillon qui cache de nombreux secrets. Il figure au patrimoine mondiale de l’UNESCO.</p>
    	</article>
    	<article class="bambous flex">
    		<figure>
    			<img src="img/bambous.png" alt="La forêt de bambous à Arashiyama" />
    		</figure>
    		<p><b>La forêt de bambous à Arashiyama : </b>La bambouseraie d’Arashiyama est sans doute la plus connus du Japon. La promenade est courte environ 500 mètres mais c’est cependant une des plus réputés et agréable de la ville.</p>
    	</article>
        <article class="fushimi flex">
            <figure>
                <img src="img/fushimi.png" alt="Le Fushimi Inari Taisha" />
            </figure>
            <p><b>Le Fushimi Inari Taisha : </b> Le sanctuaire aux 10 000 torii dans la montagne de Kyoto. La véritable attraction du domaine est le chemin de randonnée qui s’ouvre dans la vallée. Elle est balisée par des milliers de portiques vermillons appelées Torii.
            Pour l’anecdote on voit le lieu dans le film Mémoires d’une Geisha.</p>
        </article>
    </section>
</div>
<?php include "tmpl_bottom.php"; ?>