<?php include "tmpl_top.php"; ?>

<h2>Livre d'Or</h2>

<section id="livre_or">
    <article>
        <img src="img/fake_profil.jpeg" alt="profil1">
        <h4>Cisco Lan</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus totam molestiae veniam omnis reiciendis labore vitae impedit minus officiis, odio iure possimus architecto nobis excepturi magni enim nulla sequi dolores?</p>
    </article>
    <article>
        <img src="img/fake_profil.jpeg" alt="profil2">
        <h4>Jhon Douglas</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur fugit enim, accusamus nemo illum officiis, facilis totam non mollitia obcaecati ea maxime voluptatem consectetur? Dolores illum culpa consequuntur totam commodi.</p>
    </article> 
    <article>
        <img src="img/fake_profil.jpeg" alt="profil3">
        <h4>David Pro</h4>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Debitis facere totam aliquid voluptate dicta, doloremque praesentium sed molestias? Voluptate sapiente similique quod hic sint suscipit modi eum debitis, corporis itaque!</p>
    </article>
    <article>
        <img src="img/fake_profil.jpeg" alt="profil4">
        <h4>Jhone Doe</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus rem consectetur sint ipsa, nobis ipsum, magni temporibus obcaecati est reiciendis in tenetur praesentium assumenda odio ab, impedit quod deleniti sit.</p>
    </article>
</section>


<?php include "tmpl_bottom.php"; ?>