<?php include "tmpl_top.php"; ?>
<div id="osaka">
    <h2>OSAKA</h2>
    <section>
    	<article class="description">   		
			<img src="img/osaka.png" alt="OSAKA" />	
			<p><b>Thème : </b> Grande ville</p>
			<p><b>Localisation : </b>Située sur l'île de Honshu</p>
			<p><b>Accès : </b>Aéroport 	international d’Osaka, ligne de train à grande vitesse.</p>
			<p><b>Présentation : </b>Osaka veut littéralement dire "grande pente" c'est la troisième plus grande ville du Japon. Elle est complètement différente de Tokyo, c’est la ville un peu rebelle du Japon. La mentalité est un peu plus, vivante, vibrante… L’ambiance est beaucoup plus détendu. Le quartier de Dotonbori offre une ambiance festive en soirée à ne pas louper!</p>
    	</article>
    </section>
    <section class="incontournables">	
    	<h3>Les incontournables :</h3>	
    	<article class="Shinsekai flex">
			<figure>
				<img src="img/Shinsekai.png" alt="Shinsekai" />
			</figure>
				<p><b>Quartier de Shinsekai,Tsutenkaku :</b>La tour Tsutenkaku situé dans le quartier de Shinsekai est l’un des symboles de la ville: sa hauteur est de 103 mètres. L’atmosphère qui règne dans le quartier nous donne l’impression d’avoir été renvoyé dans les années 80. C’est un quartier très vivant qu’il ne faut pas manquer.</p>
    	</article>
    	<article class="shitennoji flex">
    		<figure>
    			<img src="img/shitennoji.png" alt="Shi Tenno-ji" />
    		</figure>
    		<p><b>Shi Tenno-ji : </b>Le temple est l’un des plus vieux temples bouddhistes japonais. Il a été ravagés à plusieurs reprises au fil des siècles par de nombreux incendies, mais il a été actuellement reconstruit à l’image de sa création au VI ème siècle. La balade est magnifique et très peu fréquentés.</p>
    	</article>
    	<article class="castle flex">
    		<figure>
    			<img src="img/castle.png" alt="Osaka castle et son parc" />
    		</figure>
    		<p><b>Osaka castle et son parc : </b>Le château d’Osaka est l’un des plus beaux du Japon. La beauté architecturale est sans nom. C’est ici que l’unification a pu être pensée et a débuté au 16ème siècle. Dans le donjon principal qui représente l’histoire de la ville, plusieurs oeuvres y sont exposés. Au dernier étage le panorama est à couper le souffle.</p>
    	</article>
    </section>
    <section class="incontournables">
    	<h3>Les spécialités culinaires d'Osaka :</h3>
    	<article>
			<p>La ville est réputée pour ses spécialités culinaires. En voici 2 à absolument goûter!</p>
				<div class="flex">	
					<figure>
						<a href="https://www.cuisine-japon.fr/recette-okonomiyaki/"><img class="culinaires" src="img/okonomiyaki.png" alt="L'okonomiyaki" /></a>
						<figcaption><b>L’okonomiyaki :</b> “L’omelette japonaise” ce sont des galettes que l’on sert à même le comptoir, on sert de très bonnes dans le quartier Dotonbori.</figcaption>
					</figure>
					<figure>
						<img class="culinaires" src="img/takoyaki.png" alt="Takoyaki" />
						<figcaption><b>Takoyaki :</b> C’est la star de la cuisine de rue à Osaka. Ce sont des beignets de pieuvre, recouverte de sauce puis de bonite séchée.</figcaption>
					</figure>
				</div>
    	</article>
    </section>
</div>
<?php include "tmpl_bottom.php"; ?>