<?php include 'tmpl_top.php'; ?>

<div id="phuket">
    <h2>PHUKET</h2>
    <div>
        <article class="description">
            <h3><b>La Baie de Phang Nga</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/baie-de-phang-nga.jpeg" alt="La Baie de Phang Nga">
                        <figcaption><small><em>La Baie de Phang Nga</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>Ce paysage incroyable devrait certainement être en tête de votre liste d’endroits à visiter absolument. Vous pouvez faire une croisière paresseuse sur une Jonque Chinoise ou plus près de la nature, explorer Phang Nga en canoë à travers les grottes de Phang Nga et voir quelques lagons fantastiques. Semblables à la célèbre baie d’Halong au Vietnam, ces paysages vous laisseront des souvenirs inoubliables.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>La Vieille Ville de Phuket</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/villephuket.jpg" alt="ville phuket">
                        <figcaption><small><em>vielle ville phuket</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">   
                    <p>Si il est difficile de résister à ces vieilles rues Sino-Portugaises avec leurs belles maisons de commerce et leurs magnifiques hôtels particuliers. Avec de nombreux petits cafés, boulangeries et restaurants le long de la route… La ville de Phuket est parfaite pour une demi-journée. Vous pouvez y accéder en “tuk tuk”, ou même avec le bus bleu local qui s’arrête au marché de la ville et va de là jusqu’à la rue Thalang, la plus populaire des vieilles rues de Phuket Town (la Ville de Phuket).</p> 
                </div>
            </div>   
        </article>
    </div>
    <div>
        <article class="description">
            <h3><b>Le Bouddha Géant de Phuket</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/bouddhaphuket.jpeg" alt="bouddha géant">
                        <figcaption><small><em>bouddha géant</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>Le Grand Bouddha est une statue emblématique de 45 mètres de haut en marbre blanc située au sommet de la colline de Nakkerd près de Chalong, au sud de Phuket. La route pour s’y rendre est un peu escarpée mais bien pavée, et la vue panoramique depuis le sommet vaut la peine d’être montée. Au sud, vous pouvez voir toute la baie de Chalong, jusqu’à Phang Nga et au sud, vous verrez Kata Beach. En descendant, arrêtez-vous à l’un des nombreux petits bars panoramiques pour avoir une vue d’oiseau de Karon Beach’ (la Plage de Karon). L’entrée est gratuite.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Le Temple de Chalong</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/wat_chalong.jpg" alt="temple chalong">
                        <figcaption><small><em>Temple chalong</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>CLe Wat Chalong, construit au début du 19ème siècle, est le temple bouddhiste le plus grand et le plus visité de Phuket. Le bâtiment le plus récent sur le terrain du Wat Chalong est le ‘Chedi’ de 60 mètres de haut abritant une écharde d’os de Bouddha. Les murs et les plafonds sont décorés de belles peintures illustrant la vie de Bouddha, ainsi que de nombreuses statues en or données. Comme dans tout temple de Phuket, n’oubliez pas de vous vêtir convenablement et d’enlever chaussures et casquettes lorsque vous entrez dans le temple lui-même.</p>
                </div>
            </div>
        </article>
    </div>
    <div>
        <article class="description">
            <h3><b>Le Cap de Promthep</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/cap_promthep.jpeg" alt="Le Cap de Promthep">
                        <figcaption><small><em>Le Cap de Promthep</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>Le cap de Prompthep (Prompthep Cape) n’est pas aussi grandiose qu’on pourrait s’y attendre, mais il attire toujours de nombreux touristes chaque soir pendant les heures du coucher du soleil. L’emplacement est élevé et se trouve à l’extrême sud de l’île. Il offre de belles vues sur les baies et les quelques îles environnantes. Si vous décidez d’y aller, arrêtez-vous à l’autre ‘windmill viewpoint (point de vue du moulin à vent)’ à proximité et pensez à un dîner thaï au restaurant local ‘Promthep Restaurant’.</p>
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Les Îles Similan</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/Les_Iles_Similan.jpg" alt="Les Îles Similan">
                        <figcaption><small><em>Les Îles Similan</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>L’ensemble plus impressionnant de cet archipel est sans aucun doute l’île Similan, mais celle-ci est ouverte à certaines périodes de l’année et est un peu loin. Si vous en avez l’occasion, vous devez absolument y aller. Si vous n’êtes pas sûr de vous, allez sur l’île de Phi Phi, mais il y a du monde. Les plus faciles et les plus proches sont l’île de Racha ou l’île de Coral vraiment proche.</p>
                </div>
            </div>
        </article>
    </div>
    <div>
        <article class="description">
            <h3><b>Bangla Road</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/Bangla_Road.jpg" alt="Bangla Road">
                        <figcaption><small><em>Bangla Road</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>Tout le monde devrait le voir au moins une fois. Et contrairement à ce que la plupart des gens croient, Soi Bangla n’est pas ‘Sin City for Single Men (La ville du péché pour Hommes Célibataires)’. C’est plutôt une rue colorée pleine de vie, de restaurants, de boutiques, de bars et bien sûr de filles. Maintenant si vous voulez en savoir plus, entrez dans ces fameux Bars a Go Go et voyez par vous-même de quoi il s’agit. Vous verrez souvent des couples prendre un verre… Patong est beaucoup plus facile à vivre que Bangkok ou Pattaya.</p> 
                </div>
            </div>
        </article>
        <article class="description">
            <h3><b>Jouer avec les éléphants</b></h3>
            <div class="flex_phuket">
                <div class="img_zoom_hover">
                    <figure class="img_zoom">
                        <img src="img/elephant.jpg" alt="Éléphants">
                        <figcaption><small><em>Jouer avec les éléphants</em></small></figcaption>
                    </figure>
                </div>
                <div class="texte_phuket">
                    <p>L’Elephant Jungle Sanctuary Phuket (Le sanctuaire de la jungle des éléphants de Phuket) est un endroit idéal pour jouer avec les éléphants d’une manière éthique et amusante. Dans ce sanctuaire situé pres de la plage de Nai Yang Beach, vous préparerez de la nourriture pour l’animal, vous en apprendrez un peu plus sur lui et comprendrez pourquoi le trekking doit cesser.</p>
                </div>
            </div>
        </article>
    </div>
</div>

<?php include 'tmpl_bottom.php'; ?>