<?php include "tmpl_top.php"; ?>
<div id="tokyo">
    <h2>TOKYO</h2>
	<section>
		<article class="description">
			<img src="img/Tokyo.png" alt="Tokyo" />	
			<p><b>Thème : </b>Mégalopole.</p>
			<p><b>Localisation : </b>Tokyo est la capitale du Japon, située sur la côte est de l'île principale de l'archipel japonais, Honshū.</p>
			<p><b>Accès : </b>Aéroport de Tokyo Haneda. Une fois sur place le réseau ferroviaire est très bien développé et particulièrement efficace. N’hésitez pas à emprunter le train et le métro il est très facile d’utiliser ces moyens de transports.</p>
			<p><b>Climat : </b>  Les mois les plus favorable pour se rendre à Tokyo sont juillet, août, septembre et octobre.</p>
			<p><b>Présentation : </b> Tokyo c’est la ville de la démesure! La mégalopole est l’aire urbaines la plus peuplés au monde, 38 millions de personne s’y croisent chaque jours. Pour visiter Tokyo, il est indispensable de s’organiser, la ville est immense et il serait dommage de ne pas optimiser les visites. 
			Lorsque l’on se rend à Tokyo le dépaysement est total, la culture japonaise est loin de la notre. La propreté, la discipline, et l’absence de contact font partie intégrante de leur culture.
				Nous ne pourrons bien évidemment pas tout vous présenter mais les lieux que nous avons choisis devrait vous plaire.</p>
		</article>
	</section>
	<section class="incontournables">
		<h3>Les incontournables :</h3>
		<article class="skytree flex">
			<figure>
				<img src="img/skytree.png" alt="Skytree" />
			</figure>	
			<p><b>La tour Tokyo Skytree :</b>Elle offre une vue imprenable à 360° sur la ville. C’est la plus haute tour de la ville, elle abrite un centre commerciale, des restaurants, des hôtels, un planétarium et un aquarium.</p>
		</article>
		<article class="robot flex">
			<figure>
				<img src="img/robot_restaurant.png" alt="Robot  restaurant" />
			</figure>	
			<p><b>Le robot restaurant : </b>Ce restaurant propose un show unique. Pendant 1 heure vous assisterez à un spectacle tous droits sortis d’un film d’animation. Ce spectacle unique ne vous decevra pas!</p>
		</article>
		<article class="sensoji flex">
			<figure>
				<img src="img/sensoji.png" alt="Senso-ji" />
			</figure>
			<p><b>Senso-ji : </b>C'est le plus vieux temple bouddhiste de Tokyo, il est dédié à la déesse bouddhique Kannon. Le temple a été entièrement reconstruit suite aux bombardement américain de la seconde guerre mondiale.</p>
		</article>
	</section>
</div>
<?php include "tmpl_bottom.php"; ?>